spring: 
  datasource : 
    url : jdbc:mysql://localhost:3306/cursomc?useTimezone=true&serverTimezone=UTC 
    username : root
    password : 1234
    driver-class-name : com.mysql.jdbc.Driver

  jpa :
    show-sql: true
    hibernate :
      dialect : org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
   
    